### ISSUE TITLE
subject pool: start date / end date bug

### ISSUE THREAD

**Issue by alee** [virtualcommons/vcweb#81]
start date and end date logic is still bugged, trying to save a session with an end date one hour after the start date brings up the validation error alert.

**Comment by alee** [comment]
Looks like session.end_date() isn't getting set by KO properly

**Comment by tgpatel** [comment]
hmm.. I'm not able to reproduce the issue and I don't see an alert. But I did observe that the change in date is not reflected on observable fields start_date and end_date and hence change of date doesn't work.

**Comment by tgpatel** [comment]
I was able to reproduce the issue. It happens only for newly created sessions. But the issue I believe is same as you mentioned and I mentioned in my previous comment.

**Comment by alee** [comment]
I think the KO binding may be buggy. Can you look at https://github.com/Eonasdan/bootstrap-datetimepicker/issues/219 and see if the implementation by yoanisgil will fix things? 

Please set the initial start date and end date to sane values at the beginning in model.addSession as well, something like

var initial_start_date = moment().add(1, 'days').hour(10).minute(0).format('YYYY-MM-DD HH:mm');
var initial_end_date = moment().add(1, 'days').hour(11).minute(0).format('YYYY-MM-DD HH:mm');
model.session_list.push(new SessionModel({..}))
